//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public string title { get; set; }
        public int price { get; set; }
        public int id { get; set; }
        public string albumArtURL { get; set; }
        public string songSampleURL { get; set; }
        public System.DateTime releaseDate { get; set; }
        public int genreId { get; set; }
        public int artistId { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
